# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Run Observer

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
          node-version: '12'
   
    - name: Install dependency
      run: npm ci

    - name: Show existing data
      run: git show origin/data-collector:data.json

    - name: Checkout existing data
      run: git show origin/data-collector:data.json > data/data.json 2> data/data.json || rm data/data.json

    - name: Run puppeteer
      run: npm start

    - name: Save data to branch
      uses: s0/git-publish-subdir-action@master
      env:
          REPO: self
          BRANCH: data-collector
          FOLDER: data
          SQUASH_HISTORY: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
